from typing import Protocol
from app.domain.food import Food
from app.domain.meal import Meal
from app.domain.user import UserData, UserWeight

class FoodRepo(Protocol):
    def list_foods(self) -> list[Food]: ...
    def create_food(self, food: Food) -> Food: ...
    def delete_food(self, id: int) -> bool: ...
    def edit_food(self, food: Food) -> Food | None: ...

class MealRepo(Protocol):
    def list_meals(self, start: int, end: int) -> list[Meal]: ...
    def create_meal(self, meal: Meal) -> Meal: ...
    def delete_meal(self, id: int) -> bool: ...
    def edit_meal(self, meal: Meal) -> Meal | None: ...

class UserRepo(Protocol):
    def get_user(self, user_id: int) -> UserData | None: ...
    def create_user(self, user_data: UserData) -> UserData: ...
    def edit_user(self, user_data: UserData) -> UserData | None: ...